// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weatherCommunication.proto

package com.project.weather.grpc;
public interface cityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:city)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cityName = 1;</code>
   * @return The cityName.
   */
  java.lang.String getCityName();
  /**
   * <code>string cityName = 1;</code>
   * @return The bytes for cityName.
   */
  com.google.protobuf.ByteString
      getCityNameBytes();
}
