// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weatherCommunication.proto
package com.project.weather.grpc;

public final class WeatherCommunication {
  private WeatherCommunication() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_city_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_city_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weatherData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weatherData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032weatherCommunication.proto\"\030\n\004city\022\020\n\010" +
      "cityName\030\001 \001(\t\"4\n\013weatherData\022\023\n\013tempera" +
      "ture\030\001 \001(\002\022\020\n\010pressure\030\002 \001(\00221\n\016weatherS" +
      "ervice\022\037\n\010sendCity\022\005.city\032\014.weatherDataB" +
      "\005P\001\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_city_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_city_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_city_descriptor,
        new java.lang.String[] { "CityName", });
    internal_static_weatherData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_weatherData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weatherData_descriptor,
        new java.lang.String[] { "Temperature", "Pressure", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
