// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weatherCommunication.proto
package com.project.weather.grpc;

public interface weatherDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:weatherData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float temperature = 1;</code>
   * @return The temperature.
   */
  float getTemperature();

  /**
   * <code>float pressure = 2;</code>
   * @return The pressure.
   */
  float getPressure();
}
